source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.1'
  

target 'MotionDnaSDKCocoaPodsExample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'MotionDnaSDK', :git => 'https://github.com/navisens/iOS-SDK.git'
end